# Site settings
title: The Oh' Jesses
description: |
  Eine Live-Band aus der Südwestpfalz

  welche die Freude an der Musik mit ihrem Publikum teilt

  und den Alltag für ein paar Stunden vergessen lässt
owner: The Oh' Jesses
first_published: 2022
baseurl: "" 
url: "https://theohjesses.de"
social:
  youtube-square: https://youtube.com/TheohjessesDe
  facebook-official: https://facebook.com/TheOhJesses
  instagram: https://instagram.com/theohjesses
  #email: /contact/

# Build settings
markdown: kramdown
#sass:
#  style: compressed
